#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
================================================================================
ФАЙЛ: core/hooks/__init__.py
НАЗНАЧЕНИЕ: Экспорт хуков приложения
АВТОР: Oliver Vance
ДАТА: 2026-02-15

ОПИСАНИЕ:
    Делает доступными все хуки для приложения.

ИСПОЛЬЗОВАНИЕ:
    from core.hooks import setup_error_handlers

ИСТОРИЯ ИЗМЕНЕНИЙ:
    2026-02-15 - Oliver - создание
================================================================================
"""

from core.hooks.error_handlers import setup_error_handlers

__all__ = ['setup_error_handlers']