#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
================================================================================
ФАЙЛ: utils/decorators/__init__.py
НАЗНАЧЕНИЕ: Экспорт декораторов
АВТОР: Oliver Vance
ДАТА: 2026-02-14

ОПИСАНИЕ:
    Делает доступными все декораторы через один импорт.

ИСПОЛЬЗОВАНИЕ:
    from utils.decorators import login_required, admin_required

ИСТОРИЯ ИЗМЕНЕНИЙ:
    2026-02-14 - Oliver - создание
================================================================================
"""

from utils.decorators.login_required import (
    login_required,
    admin_required,
    get_current_user_id,
    request_wants_json
)

__all__ = [
    'login_required',
    'admin_required',
    'get_current_user_id',
    'request_wants_json',
]